In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {"criterion": ["squared_error", "absolute_error", "friedman_mse"],
    "max_features": ["sqrt", "log2", None],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'}:

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.045546,0.002366,0.019935,0.006610,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.689027,0.625699,0.733559,0.718940,0.672957,0.688036,0.037793,7
1,0.038651,0.010044,0.014710,0.003846,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.713616,0.587784,0.684251,0.693234,0.664014,0.668580,0.043429,12
2,0.034675,0.014128,0.019786,0.004109,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.749018,0.670744,0.708631,0.693403,0.722174,0.708794,0.026388,1
3,0.027636,0.007258,0.014590,0.003904,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.662175,0.497590,0.617708,0.656450,0.727365,0.632258,0.075990,17
4,0.054556,0.006071,0.016676,0.006050,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.711846,0.646421,0.727324,0.734049,0.669281,0.697784,0.034165,4
5,0.037365,0.003104,0.013857,0.004948,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.686097,0.606141,0.700109,0.700832,0.726135,0.683863,0.040950,8
6,0.143510,0.011701,0.016123,0.005149,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.607737,0.496275,0.680882,0.678394,0.738946,0.640447,0.083226,15
7,0.109372,0.010168,0.016802,0.008131,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.678815,0.519626,0.451447,0.716740,0.663692,0.606064,0.102216,18
8,0.137931,0.020352,0.016012,0.005577,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.646285,0.534611,0.712397,0.727507,0.552350,0.634630,0.079478,16
9,0.101401,0.004702,0.017884,0.004783,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.662743,0.566648,0.677498,0.757020,0.668011,0.666384,0.060500,13
10,0.246647,0.022257,0.016006,0.007393,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.731652,0.585826,0.687392,0.727420,0.738135,0.694085,0.056970,5
11,0.181262,0.015879,0.018731,0.005148,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.669071,0.629468,0.730657,0.756629,0.758053,0.708775,0.051114,2
12,0.030626,0.005901,0.021264,0.007669,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.690623,0.627800,0.765422,0.641710,0.686128,0.682336,0.048189,9
13,0.028605,0.005522,0.016774,0.004839,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.728477,0.563647,0.672777,0.737529,0.706224,0.681731,0.063123,10
14,0.032149,0.003112,0.016095,0.004000,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.697884,0.595178,0.693666,0.692996,0.699155,0.675776,0.040368,11
15,0.024693,0.005455,0.015516,0.006274,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.653635,0.566785,0.734092,0.676728,0.639347,0.654118,0.054319,14
16,0.049075,0.004189,0.015197,0.004608,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.726042,0.643381,0.735212,0.740171,0.679478,0.704857,0.037525,3
17,0.033622,0.003322,0.012092,0.004349,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.715507,0.617535,0.697684,0.712916,0.706025,0.689934,0.036723,6

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 40
BMI: 25
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[19515.5416]

C:\Users\ragav\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(